name: DocketMate_Sandbox
options:
  bundleIdPrefix: com.products
  deploymentTarget:
    macOS: 13.5
targets:
  DocketMate_Sandbox:
    type: application
    platform: macOS
    sources: Sources
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: DocketMate Sandbox
        LSApplicationCategoryType: public.app-category.productivity
