name: FinanceMate_Sandbox
options:
  bundleIdPrefix: com.products
  deploymentTarget:
    macOS: 13.5
targets:
  FinanceMate_Sandbox:
    type: application
    platform: macOS
    sources: Sources
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: FinanceMate Sandbox
        LSApplicationCategoryType: public.app-category.productivity
